version: '3'

services:

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    environment:
      - INFLUXD_BOLT_PATH=/var/influxdb2/influxdb.bolt
      - INFLUXD_ENGINE_PATH=/var/influxdb2/engine
    volumes:
      - ./influxdb2:/var/influxdb2/
    ports:
      - 8086:8086

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    user: "1000"
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - influxdb    
  
