version: '3'

services:

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    # Had to explicitly set the paths via the
    # environment variables to know how to do
    # the volume mapping later
    environment:
      - INFLUXD_BOLT_PATH=/var/influxdb2/influxdb.bolt
      - INFLUXD_ENGINE_PATH=/var/influxdb2/engine
    volumes:
      - ./influxdb2:/var/influxdb2/
    ports:
      - 8086:8086

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    # run id -u to get the unix user id, then set it here.
    # this allows the grafana container permissions to write
    # to the mapped host volume. Otherwise, you will get access
    # denied errprs
    user: "1000"
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - influxdb    
  
